### ISSUE TITLE
缺少人类评估调整后的权重系数集成

### ISSUE THREAD

**Issue by franky519** [Quehry/HelloBench#3]
在opencompass 和 这个github仓库里都缺少人类评估调整后的权重系数集成

**Comment by Quehry** [comment]
Hello @franky519,
Indeed, the integration of weighted scores is missing in this repository, but they are available in OpenCompass. For details, please refer to: https://github.com/open-compass/opencompass/blob/main/opencompass/datasets/subjective/hellobench.py. We will add the weighted scores to this repository as soon as possible. Thanks for your attention.

**Comment by franky519** [comment]
Thanks. 
But "HelloEval is also in an unusable state within OpenCompass, likely due to an update of the official OpenCompass library. I'm going crazy. The warning I received during usage was:
UserWarning: Starting from v0.4.0,
all AMOTIC configuration files currently located in ./configs/datasets, ./configs/models, and ./configs/summarizers will be migrated to the opencompass/configs/ package. Please update your configuration file paths accordingly.
_warn_about_config_migration()
signal.SIGALRM is not available on this platform"

**Comment by franky519** [comment]
Moreover, the datasets in OpenCompass are different from those in this GitHub repository. The datasets in this repository do not have a "category" field, while in the OpenCompass repository, the "requirements" field is placed as a separate key.

**Comment by Quehry** [comment]
> Moreover, the datasets in OpenCompass are different from those in this GitHub repository. The datasets in this repository do not have a "category" field, while in the OpenCompass repository, the "requirements" field is placed as a separate key.

For this, the content of datasets remain the same, HelloBench has different keys for the reason to fit the requirements of opencompass frameworks.

**Comment by Quehry** [comment]
> Thanks. But "HelloEval is also in an unusable state within OpenCompass, likely due to an update of the official OpenCompass library. I'm going crazy. The warning I received during usage was: UserWarning: Starting from v0.4.0, all AMOTIC configuration files currently located in ./configs/datasets, ./configs/models, and ./configs/summarizers will be migrated to the opencompass/configs/ package. Please update your configuration file paths accordingly. _warn_about_config_migration() signal.SIGALRM is not available on this platform"


It seems that this warning does not affect your program execution? I encountered a similar report while running the program, but it was able to execute normally. Here is my log:

/quehaoran/opencompass/opencompass/__init__.py:17: UserWarning: Starting from v0.4.0, all AMOTIC configuration files currently located in `./configs/datasets`, `./configs/models`, and `./configs/summarizers` will be migrated to the `opencompass/configs/` package. Please update your configuration file paths accordingly.
  _warn_about_config_migration()
11/18 16:55:03 - OpenCompass - INFO - Task [qwen2.5-7b-instruct-hf/HelloBench-chat]
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]
Loading checkpoint shards:  25%|██▌       | 1/4 [00:04<00:14,  4.84s/it]
Loading checkpoint shards:  50%|█████     | 2/4 [00:11<00:11,  5.81s/it]
Loading checkpoint shards:  75%|███████▌  | 3/4 [00:18<00:06,  6.28s/it]
Loading checkpoint shards: 100%|██████████| 4/4 [00:23<00:00,  5.73s/it]
Loading checkpoint shards: 100%|██████████| 4/4 [00:23<00:00,  5.76s/it]
11/18 16:56:56 - OpenCompass - INFO - using stop words: ['<|im_end|>']
11/18 16:56:59 - OpenCompass - INFO - Start inferencing [qwen2.5-7b-instruct-hf/HelloBench-chat]
[2024-11-18 16:56:59,605] [opencompass.openicl.icl_inferencer.icl_gen_inferencer] [INFO] Starting build dataloader
[2024-11-18 16:56:59,606] [opencompass.openicl.icl_inferencer.icl_gen_inferencer] [INFO] Starting inference process...

  0%|          | 0/19 [00:00<?, ?it/s]/usr/local/lib/python3.10/dist-packages/transformers/generation/configuration_utils.py:492: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.7` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/generation/configuration_utils.py:497: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0.8` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/generation/configuration_utils.py:509: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `20` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

  5%|▌         | 1/19 [04:14<1:16:29, 254.96s/it]
 11%|█         | 2/19 [05:24<41:15, 145.60s/it]  
 16%|█▌        | 3/19 [06:00<25:30, 95.67s/it] 
 21%|██        | 4/19 [25:27<2:09:39, 518.65s/it]
 26%|██▋       | 5/19 [26:22<1:22:00, 351.49s/it]
 32%|███▏      | 6/19 [27:21<54:37, 252.11s/it]  
 37%|███▋      | 7/19 [28:40<39:05, 195.48s/it]
 42%|████▏     | 8/19 [30:05<29:23, 160.34s/it]
 47%|████▋     | 9/19 [31:30<22:47, 136.72s/it]
 53%|█████▎    | 10/19 [34:05<21:20, 142.27s/it]
 58%|█████▊    | 11/19 [36:09<18:15, 136.94s/it]
 63%|██████▎   | 12/19 [37:27<13:52, 118.96s/it]
 68%|██████▊   | 13/19 [39:38<12:15, 122.64s/it]
 74%|███████▎  | 14/19 [41:12<09:28, 113.73s/it]
 79%|███████▉  | 15/19 [42:26<06:47, 101.97s/it]
 84%|████████▍ | 16/19 [45:30<06:20, 126.67s/it]
 89%|████████▉ | 17/19 [47:01<03:51, 115.94s/it]
 95%|█████████▍| 18/19 [1:05:08<06:47, 407.70s/it]
100%|██████████| 19/19 [1:05:58<00:00, 300.08s/it]
100%|██████████| 19/19 [1:05:58<00:00, 208.32s/it]
11/18 18:02:57 - OpenCompass - INFO - time elapsed: 4073.79s

**Comment by franky519** [comment]
I understand... I'm still learning the ropes. I'm wondering if there's a specific reason why OpenCompass needs a Linux environment. I've been running it on my local machine, but I'm encountering some issues.
